server.port=${PORT:8080}
logging.level.org.atmosphere = warn
spring.mustache.check-template-location = false
# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true
# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
vaadin.whitelisted-packages = com.vaadin,org.vaadin,dev.hilla,com.example.application
spring.jpa.defer-datasource-initialization = true
vaadin.productionMode=true
# vaadin.productionMode=false
 # debug=true
vaadin.frontend.hotdeploy.max-bundle-size=10MB
svg.output.directory=generated_svgs
# svg.output.directory=/var/myapp/generated_svgs
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:file:./data/svgdb
# spring.datasource.url=jdbc:h2:mem:svgdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# Active profile: dev or prod
spring.profiles.active=dev
# spring.profiles.active=prod
# Base domain used for tenant URLs
app.base-domain=kjwlocal.com
# API path used for all tenants
app.api-path=/api/drawing-client/recieve-svg
app.external-api-path=http://host.docker.internal
# app.external-api-base-url=http://localhost:8089
app.drawing-api-token=drawing-api-token-change-it